const productDatas = [
  {
    id: 1,
    picture: "images/Cardpic/c-sharp.jpg",
    courseName: "آموزش جامع C#",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 1580000,
    rating: 5,
    time: 70,
    courseText:
      "امروزه Net. به یک چارچوب کاملا بدیع برای تولید و توسعه انواع برنامه ها مبدل شده است. برنامه هایی که با استفاده از Net. تولید شده است، حجم وسیعی از بازار نرم افزار ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 2,
    picture: "images/Cardpic/DataMining.jpg",
    courseName: "آموزش Data Mining",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 650000,
    rating: 5,
    time: 80,
    courseText:
      "داده‌ها امروز نقش زیادی در موفقیت یک کسب‌وکار و پیش‌برد اهداف یک سازمان دارد. سازمان‌ها به متخصصان علوم داده نیاز دارند تا با استفاده از تحلیل و پردازش داده افق‌های روش‌تری",
    startDate: "1401/12/12",
    capacity: "50",
    category: "dataMining",
  },
  {
    id: 3,
    picture: "images/Cardpic/php.jpg",
    courseName: "آموزش جامع php",
    courseInsructor: "ایلان ماسک",
    coursePrice: 850000,
    rating: 4,
    time: 200,
    courseText:
      "زبان برنامه نویسی PHP یکی از زبان های برنامه نویسی سمت سرور است که کاربرد اصلی آن، در پیاده سازی وب سایت های دینامیکی (پویا) است. بازنویسی هسته PHP و ایجاد موتور پردازشی زن",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 4,
    picture: "images/Cardpic/golang.jpg",
    courseName: "آموزش جامع go",
    courseInsructor: "مرحوم جابز",
    coursePrice: 140000,
    rating: 3,
    time: 250,
    courseText:
      "زبان برنامه‌نویسی Go (یا Golang) یک زبان برنامه‌نویسی متن‌باز (Open Source) است که ساخت نرم‌افزار را ساده، قابل‌اعتماد و بهینه می‌کند. Golang زبانی است که توسط شرکت Google طراحی شده‌است و در حال حاضر، ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 5,
    picture: "images/Cardpic/JavaScript.jpg",
    courseName: "آموزش javaScript",
    courseInsructor: "دکتر باقری",
    coursePrice: 120000,
    rating: 1,
    time: 500,
    courseText:
      "جاوا اسکریپت یک زبان اسکریپت نویسی تحت وب است، که در میلیون ها صفحه وب برای اضافه کردن توابع، اعتبار سنجی فرم ها، ارتباط برقرار کردن با سرور و… استفاده شده است",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 6,
    picture: "images/Cardpic/photoshop.jpg",
    courseName: "آموزش photoshop",
    courseInsructor: "حامد نظری",
    coursePrice: 360000,
    rating: 5,
    time: 5,
    courseText:
      "رم افزار فتوشاپ امروزه یکی از بهترین و قدرتمندترین نرم افزار های گرافیکی برای طراحی به شمار میرود.امروزه اکثر طراحان حوضه گرافیک ازاین نرم افزار استفاده می کنند.نرم افزاری که بازار بسیار عالی برای کار و ک",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 7,
    picture: "images/Cardpic/uiDesign.jpg",
    courseName: "آموزش رابط کاربری",
    courseInsructor: " حامد نظری",
    coursePrice: 700000,
    rating: 5,
    time: 80,
    courseText:
      "این صفحه متعلق به دوره آموزش طراحی UI مرجع آموزش UI و UX فارسی می باشد که با نام طراحی اصولی رابط کاربری شناخته می شود. حتی اگر قصد خرید این دوره آموزشی را ندارید پیشنهاد می کنیم مطالب موجود در این ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 8,
    picture: "images/Cardpic/java.jpeg",
    courseName: "آموزش جامع java",
    courseInsructor: "استیون هاوکینگ",
    coursePrice: 350000,
    rating: 4,
    time: 2,
    courseText:
      "مجموعه فیلم های آموزشی برنامه نویسی جاوا در طی ۲۳ درس، مخاطب را به صورت کامل با زبان برنامه نویسی جاوا و امکانات مختلف آن آشنا می کند. در این مجموعه",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 9,
    picture: "images/Cardpic/python.jpg",
    courseName: "آموزش python",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 360000,
    rating: 5,
    time: 600,
    courseText:
      "در این آموزش قصد داریم پایتون را از پایه آموزش دهیم و سعی می کنیم تمام مطالب مقدماتی لازم برای برنامه نویسی با پایتون را پوشش دهیم. چرا که برای انجام هر کاری با پایتون، نیازمند آشنایی",
    startDate: "1401/12/12",
    capacity: "50",
    category: "AI",
  },
  {
    id: 10,
    picture: "images/Cardpic/reactJS.jpg",
    courseName: "آموزش ReactJS",
    courseInsructor: " مهدی اصغری ",
    coursePrice: 700000,
    rating: 5,
    time: 250,
    courseText:
      "در این دوره قصد داریم  ReactJs رو در سطح مقدماتی و قابل قبولی به شما آموزش بدیم. ReactJs اساسا یک کتابخانه open-source جاوا اسکریپته که برای ایجاد رابط کاربری مخصوصا برای برنامه های ت",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 11,
    picture: "images/Cardpic/unity.jpg",
    courseName: "آموزش جامع Unity",
    courseInsructor: "مارک زاکربرگ",
    coursePrice: 350000,
    rating: 3,
    time: 70,
    courseText:
      "ر این دوره ، به مفاهیمی که باید برای ساخت یک بازی دوبعدی با آن آشنا شوید تا حدود زیادی پرداخته میشود و در این دوره قصد بر یادگیری بازیسازی دوبعدی نیست و تنها بعنوان",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 12,
    picture: "images/Cardpic/c-sharp.jpg",
    courseName: "آموزش جامع C#",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 1580000,
    rating: 5,
    time: 50,
    courseText:
      "امروزه Net. به یک چارچوب کاملا بدیع برای تولید و توسعه انواع برنامه ها مبدل شده است. برنامه هایی که با استفاده از Net. تولید شده است، حجم وسیعی از بازار نرم افزار ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "dataMining",
  },
  {
    id: 13,
    picture: "images/Cardpic/DataMining.jpg",
    courseName: "آموزش Data Mining",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 650000,
    rating: 5,
    time: 250,
    courseText:
      "داده‌ها امروز نقش زیادی در موفقیت یک کسب‌وکار و پیش‌برد اهداف یک سازمان دارد. سازمان‌ها به متخصصان علوم داده نیاز دارند تا با استفاده از تحلیل و پردازش داده افق‌های روش‌تری",
    startDate: "1401/12/12",
    capacity: "50",
    category: "dataMining",
  },
  {
    id: 14,
    picture: "images/Cardpic/php.jpg",
    courseName: "آموزش جامع php",
    courseInsructor: "ایلان ماسک",
    coursePrice: 850000,
    rating: 2,
    time: 90,
    courseText:
      "زبان برنامه نویسی PHP یکی از زبان های برنامه نویسی سمت سرور است که کاربرد اصلی آن، در پیاده سازی وب سایت های دینامیکی (پویا) است. بازنویسی هسته PHP و ایجاد موتور پردازشی زن",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 15,
    picture: "images/Cardpic/golang.jpg",
    courseName: "آموزش جامع go",
    courseInsructor: "مرحوم جابز",
    coursePrice: 140000,
    rating: 3,
    time: 250,
    courseText:
      "زبان برنامه‌نویسی Go (یا Golang) یک زبان برنامه‌نویسی متن‌باز (Open Source) است که ساخت نرم‌افزار را ساده، قابل‌اعتماد و بهینه می‌کند. Golang زبانی است که توسط شرکت Google طراحی شده‌است و در حال حاضر، ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 16,
    picture: "images/Cardpic/JavaScript.jpg",
    courseName: "آموزش javaScript",
    courseInsructor: "دکتر باقری",
    coursePrice: 120000,
    rating: 2,
    time: 160,
    courseText:
      "جاوا اسکریپت یک زبان اسکریپت نویسی تحت وب است، که در میلیون ها صفحه وب برای اضافه کردن توابع، اعتبار سنجی فرم ها، ارتباط برقرار کردن با سرور و… استفاده شده است",
    startDate: "1401/12/12",
    capacity: "50",
    category: "AI",
  },
  {
    id: 17,
    picture: "images/Cardpic/photoshop.jpg",
    courseName: "آموزش photoshop",
    courseInsructor: "حامد نظری",
    coursePrice: 360000,
    rating: 5,
    time: 140,
    courseText:
      "رم افزار فتوشاپ امروزه یکی از بهترین و قدرتمندترین نرم افزار های گرافیکی برای طراحی به شمار میرود.امروزه اکثر طراحان حوضه گرافیک ازاین نرم افزار استفاده می کنند.نرم افزاری که بازار بسیار عالی برای کار و ک",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 18,
    picture: "images/Cardpic/uiDesign.jpg",
    courseName: "آموزش رابط کاربری",
    courseInsructor: " حامد نظری",
    coursePrice: 700000,
    rating: 5,
    time: 250,
    courseText:
      "این صفحه متعلق به دوره آموزش طراحی UI مرجع آموزش UI و UX فارسی می باشد که با نام طراحی اصولی رابط کاربری شناخته می شود. حتی اگر قصد خرید این دوره آموزشی را ندارید پیشنهاد می کنیم مطالب موجود در این ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 19,
    picture: "images/Cardpic/java.jpeg",
    courseName: "آموزش جامع java",
    courseInsructor: "استیون هاوکینگ",
    coursePrice: 350000,
    rating: 3,
    time: 60,
    courseText:
      "مجموعه فیلم های آموزشی برنامه نویسی جاوا در طی ۲۳ درس، مخاطب را به صورت کامل با زبان برنامه نویسی جاوا و امکانات مختلف آن آشنا می کند. در این مجموعه",
    startDate: "1401/12/12",
    capacity: "50",
    category: "machineLearning",
  },
  {
    id: 20,
    picture: "images/Cardpic/python.jpg",
    courseName: "آموزش python",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 360000,
    rating: 5,
    time: 30,
    courseText:
      "در این آموزش قصد داریم پایتون را از پایه آموزش دهیم و سعی می کنیم تمام مطالب مقدماتی لازم برای برنامه نویسی با پایتون را پوشش دهیم. چرا که برای انجام هر کاری با پایتون، نیازمند آشنایی",
    startDate: "1401/12/12",
    capacity: "50",
    category: "AI",
  },
  {
    id: 21,
    picture: "images/Cardpic/reactJS.jpg",
    courseName: "آموزش ReactJS",
    courseInsructor: " مهدی اصغری ",
    coursePrice: 700000,
    rating: 5,
    time: 250,
    courseText:
      "در این دوره قصد داریم  ReactJs رو در سطح مقدماتی و قابل قبولی به شما آموزش بدیم. ReactJs اساسا یک کتابخانه open-source جاوا اسکریپته که برای ایجاد رابط کاربری مخصوصا برای برنامه های ت",
    startDate: "1401/12/12",
    capacity: "50",
    category: "machineLearning",
  },
  {
    id: 22,
    picture: "images/Cardpic/uiDesign.jpg",
    courseName: "آموزش رابط کاربری",
    courseInsructor: " حامد نظری",
    coursePrice: 700000,
    rating: 5,
    time: 80,
    courseText:
      "این صفحه متعلق به دوره آموزش طراحی UI مرجع آموزش UI و UX فارسی می باشد که با نام طراحی اصولی رابط کاربری شناخته می شود. حتی اگر قصد خرید این دوره آموزشی را ندارید پیشنهاد می کنیم مطالب موجود در این ",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
  {
    id: 23,
    picture: "images/Cardpic/java.jpeg",
    courseName: "آموزش جامع java",
    courseInsructor: "استیون هاوکینگ",
    coursePrice: 350000,
    rating: 4,
    time: 2,
    courseText:
      "مجموعه فیلم های آموزشی برنامه نویسی جاوا در طی ۲۳ درس، مخاطب را به صورت کامل با زبان برنامه نویسی جاوا و امکانات مختلف آن آشنا می کند. در این مجموعه",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 24,
    picture: "images/Cardpic/python.jpg",
    courseName: "آموزش python",
    courseInsructor: "دکتر بحرالعلوم",
    coursePrice: 360000,
    rating: 5,
    time: 600,
    courseText:
      "در این آموزش قصد داریم پایتون را از پایه آموزش دهیم و سعی می کنیم تمام مطالب مقدماتی لازم برای برنامه نویسی با پایتون را پوشش دهیم. چرا که برای انجام هر کاری با پایتون، نیازمند آشنایی",
    startDate: "1401/12/12",
    capacity: "50",
    category: "AI",
  },
  {
    id: 25,
    picture: "images/Cardpic/reactJS.jpg",
    courseName: "آموزش ReactJS",
    courseInsructor: " مهدی اصغری ",
    coursePrice: 700000,
    rating: 5,
    time: 250,
    courseText:
      "در این دوره قصد داریم  ReactJs رو در سطح مقدماتی و قابل قبولی به شما آموزش بدیم. ReactJs اساسا یک کتابخانه open-source جاوا اسکریپته که برای ایجاد رابط کاربری مخصوصا برای برنامه های ت",
    startDate: "1401/12/12",
    capacity: "50",
    category: "Programming",
  },
  {
    id: 26,
    picture: "images/Cardpic/unity.jpg",
    courseName: "آموزش جامع Unity",
    courseInsructor: "مارک زاکربرگ",
    coursePrice: 350000,
    rating: 3,
    time: 70,
    courseText:
      "ر این دوره ، به مفاهیمی که باید برای ساخت یک بازی دوبعدی با آن آشنا شوید تا حدود زیادی پرداخته میشود و در این دوره قصد بر یادگیری بازیسازی دوبعدی نیست و تنها بعنوان",
    startDate: "1401/12/12",
    capacity: "50",
    category: "GraphicsAndDesign",
  },
];

export default productDatas;
